server:
    port: 8081
spring:
    datasource:
        password: admin
        url: jdbc:mysql://localhost:3306/deptdatabase?useSSL=false
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
        show-sql: true
      
# Test Details for Development Environment
test:
  details: Department service details for development environment [From GitHub]
  engineer: John Doe01
  department: Development Testing [Dept service]
  engineerContact:
    email: testengineer01.dev@example.com
    phone: 111-456-7890       
