server:
    port: 8082
spring:
    datasource:
        password: admin
        url: jdbc:mysql://localhost:3306/employeesdatabase?useSSL=false
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                
# Test Details for Development Environment
test:
  details: Employee service details for development environment [From GitHub]
  engineer: John Doe
  department: Development Testing
  engineerContact:
    email: testengineer.dev@example.com
    phone: 123-456-7890                
